//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShopScheduler.Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PetShopScheduler.Domain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve ser informado o nome da raça.
        /// </summary>
        internal static string BreedDescriptionError {
            get {
                return ResourceManager.GetString("BreedDescriptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O estabelecimento deve ser informado.
        /// </summary>
        internal static string EstablishmentCanNotBeNull {
            get {
                return ResourceManager.GetString("EstablishmentCanNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve ser informado a descrição do estabelecimento.
        /// </summary>
        internal static string EstablishmentDescriptionError {
            get {
                return ResourceManager.GetString("EstablishmentDescriptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve ser informado o CNPJ do estabelecimento.
        /// </summary>
        internal static string EstablishmentDocumentError {
            get {
                return ResourceManager.GetString("EstablishmentDocumentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CNPJ informado para o estabelecimento é inválido.
        /// </summary>
        internal static string EstablishmentDocumentInvalidErro {
            get {
                return ResourceManager.GetString("EstablishmentDocumentInvalidErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve ser informado o nome do estabelecimento.
        /// </summary>
        internal static string EstablishmentNameError {
            get {
                return ResourceManager.GetString("EstablishmentNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve ser informado o endereço do dono do animal de estimação.
        /// </summary>
        internal static string OwnerPetAddressError {
            get {
                return ResourceManager.GetString("OwnerPetAddressError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve ser informado o número do endereço do dono do animal de estimação.
        /// </summary>
        internal static string OwnerPetAddressNumberError {
            get {
                return ResourceManager.GetString("OwnerPetAddressNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O dono do animal de estimação deve ser informado.
        /// </summary>
        internal static string OwnerPetCanNotBeNull {
            get {
                return ResourceManager.GetString("OwnerPetCanNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve ser informada a cidade do dono do animal de estimação.
        /// </summary>
        internal static string OwnerPetCityError {
            get {
                return ResourceManager.GetString("OwnerPetCityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve ser informado o bairro do dono do animal de estimação.
        /// </summary>
        internal static string OwnerPetDistrictError {
            get {
                return ResourceManager.GetString("OwnerPetDistrictError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve ser informado o documento do dono do animal de estimação.
        /// </summary>
        internal static string OwnerPetDocumentError {
            get {
                return ResourceManager.GetString("OwnerPetDocumentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CPF informado é inválido.
        /// </summary>
        internal static string OwnerPetDocumentInvalidError {
            get {
                return ResourceManager.GetString("OwnerPetDocumentInvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve ser informado o nome do dono do animal de estimação.
        /// </summary>
        internal static string OwnerPetNameError {
            get {
                return ResourceManager.GetString("OwnerPetNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve ser informado um número de teledone do dono do animal de estimação.
        /// </summary>
        internal static string OwnerPetPhoneNumberError {
            get {
                return ResourceManager.GetString("OwnerPetPhoneNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve ser informado o estado do dono do animal de estimação.
        /// </summary>
        internal static string OwnerPetStateError {
            get {
                return ResourceManager.GetString("OwnerPetStateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve ser informado o CEP do dono do animal de estimação.
        /// </summary>
        internal static string OwnerPetZipCodeError {
            get {
                return ResourceManager.GetString("OwnerPetZipCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de nascimento do animal de estimação deve ser menor ou igual a hoje.
        /// </summary>
        internal static string PetBirthDateError {
            get {
                return ResourceManager.GetString("PetBirthDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve ser informada a raça do animal de estimação.
        /// </summary>
        internal static string PetBreedError {
            get {
                return ResourceManager.GetString("PetBreedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve ser informado o nome do animal de estimação.
        /// </summary>
        internal static string PetNameError {
            get {
                return ResourceManager.GetString("PetNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve ser informado um dono para o animal de estimação.
        /// </summary>
        internal static string PetNeedOwnerError {
            get {
                return ResourceManager.GetString("PetNeedOwnerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O peso do animal de estimação deve ser maior que zero.
        /// </summary>
        internal static string PetWeigthError {
            get {
                return ResourceManager.GetString("PetWeigthError", resourceCulture);
            }
        }
    }
}
